spring.datasource.url=jdbc:postgresql://gpx-file-processor-db.cju60w8ysfz7.us-east-2.rds.amazonaws.com:5432/gpx_file_processor
spring.datasource.username=postgres
spring.datasource.password=Caesar-3231

spring.rabbitmq.host=52.36.193.27
spring.rabbitmq.port=5672
spring.rabbitmq.username=host
spring.rabbitmq.password=caesar-123

s3.bucket-name=gpx-file-processor-kj
s3.region=us-west-2