spring.application.name=GPX-File-Processor

spring.datasource.url=jdbc:postgresql://localhost:5433/gpx_file_processor
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=local